name: Release Notes Syncing

on:
  release:
    types: [ published ]
  
jobs:

  create-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - name: avx2
            instance_type: c5.large
          - name: avx512
            instance_type: c6i.large
          - name: neon
            instance_type: c6g.large
          - name: sve2
            instance_type: c7g.large
        
    steps:

      - name: Checkout PR commit 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}
      
          
      - name: Launch Endee Server
        id: launch 
        run: |
            ENDEE_INSTANCE_ID=$(aws ec2 run-instances \
              --region ${{ vars.AWS_REGION }} \
              --image-id ${{ vars.AMI_ID }} \
              --instance-type "${{ matrix.arc.instance_type }}" \
              --key-name ${{ secrets.ENDEE_PEM }} \
              --security-group-ids ${{ secrets.VECTORDBBENCH_SERVER_GROUP_ID }} \
              --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
              --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":30,"VolumeType":"gp3"}}]' \
              --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${{ matrix.arc.name }}}]" \
              --query 'Instances[0].InstanceId' \
              --output text)
          
            aws ec2 wait instance-running \
              --instance-ids $ENDEE_INSTANCE_ID

            IP=$(aws ec2 describe-instances \
              --instance-ids $ENDEE_INSTANCE_ID \
              --query 'Reservations[0].Instances[0].PublicIpAddress' \
              --output text)
            echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: write PEM file
        run: |
          echo "${{ secrets.ENDEE_SSH_PRIVATE_KEY }}" > "~/.ssh/${{ secrets.ENDEE_PEM }}"
          chmod 400 "~/.ssh/${{ secrets.ENDEE_PEM }}"
          echo "Endee PEM file Created"
      
      - name: wait for ssh to be ready 
        run: |
          for i in {1..5}; do
            if ssh -i "$ENDEE_PEM_FILE" -o StrictHostKeyChecking=no -o ConnectTimeout=5 -o BatchMode=yes ubuntu@"$ENDEE_IP" "echo ok" 2>/dev/null; then
              echo "SSH ready on ${{ matrix.arc.name }} Endee @ $ENDEE_IP"
              ENDEE_SSH_READY=true
              break
            fi
            echo "Failed $i/5 retrying in 1 second..."
            sleep 1
          done
          if [ "$ENDEE_SSH_READY" = false ]; then
            echo "Failed to SSH to Endee Server"
            exit 1
          fi

      - name: Run and Build Endee Binary
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.ENDEE_PEM }} ubuntu@${{ steps.launch.outputs.ip }} << 'EOF'
            set -euo pipefail 
            sudo aptget update -y
            cd ~
            # CLONE ENDEE REPO 
            git clone https://github.com/endee-io/endee.git

            cd endee

            arc=\$(grep -o 'avx2\|avx512\|neon\|sve2' /proc/cpuinfo | sort -u)
            echo "ARCHITECTURE: \$arc"

            # UPDATE ULIMIT OF OS 
            ulimit -n 5000

            if [[ "${{ matrix.arch.name }}" == "avx2" || "${{ matrix.arch.name }}" == "avx512" ]]; then
              ./install.sh --release --avx2
            else
              ./install.sh --release --neon
            fi

          EOF




            
        
      










